name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login GHCR
        run: |
          echo $CR_PAT | docker login ghcr.io -u ${{ secrets.User }} --password-stdin
        env:
          CR_PAT: ${{ secrets.PAT }}
      - name: Build Docker Image
        run: |
          docker build . --file NetGpt.Api/Dockerfile --tag ghcr.io/tiaringhio/netgpt:latest
          docker push ghcr.io/tiaringhio/netgpt:latest